[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "mysql80"]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "php artisan config:clear",
  "php artisan key:generate",
  "php artisan migrate --force || true"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
